version: "3.8"

services:
  student-data-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-data-gui
    ports:
      - "8080:8080"
    environment:
      - NICEGUI_HOST=0.0.0.0
      - NICEGUI_PORT=8080
      - PYTHONPATH=/app
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp/home
    volumes:
      # Mount host directory for persistent data storage
      - ./data:/app/data
      # Optional: mount specific database location
      - ./database:/app/database
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8080')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - student-net

networks:
  student-net:
    driver: bridge

# Optional volumes for explicit volume management
volumes:
  student-data:
    driver: local
  student-database:
    driver: local
