services:
  student-data-gui:
    build:
      context: .
      dockerfile: Dockerfile.podman
    container_name: student-data-gui
    ports:
      - "8080:8080"
    environment:
      - NICEGUI_HOST=0.0.0.0
      - NICEGUI_PORT=8080
      - PYTHONPATH=/app
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/app/home
      - XDG_RUNTIME_DIR=/tmp/runtime
    volumes:
      - ./app_home:/app_home:Z
      - ./json_Files:/app/json_Files:Z
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "/app/venv/bin/python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8080')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - student-net

networks:
  student-net:
    driver: bridge

volumes:
  student-data:
    driver: local
  student-database:
    driver: local
  student-logs:
    driver: local
