# Docker Compose override file for Podman compatibility
# This file provides Podman-specific configurations and can be used
# alongside the main compose.yaml file

version: "3.8"

services:
  student-data-gui:
    # Remove user specification for rootless Podman
    # user: ""

    # Alternative volume mounts for Podman rootless
    volumes:
      - ./data:/app/data:Z
      - ./database:/app/database:Z

    # Podman-specific security options
    security_opt:
      - label=disable

    # Use host networking for Podman if needed
    # network_mode: host

    # Alternative environment variables for Podman
    environment:
      - NICEGUI_HOST=0.0.0.0
      - NICEGUI_PORT=8080
      - PYTHONPATH=/app
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp/home
      - PODMAN_USERNS=keep-id

    # Simplified healthcheck for Podman
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Additional capabilities that might be needed
    cap_add:
      - SYS_ADMIN

    # Tmpfs mounts for better performance
    tmpfs:
      - /tmp:noexec,nosuid,size=1G
      - /var/tmp:noexec,nosuid,size=1G
